--!strict
-- 躲猫猫游戏道具配置
-- 复用现有的ConfigDatas系统

local Items = {
	-- ============ 通用道具 ============
	{
		id = "SpeedPotion",
		name = "加速饮料",
		description = "速度+30%持续5秒",
		type = "Common",
		team = "Both",
		price = 200,
		rarity = "Common",
		effect = {
			speedBonus = 0.3,
			duration = 5,
		},
		icon = "rbxassetid://0",
		maxStack = 3,
	},
	{
		id = "SmokeBomb",
		name = "烟雾弹",
		description = "制造视觉遮挡5秒",
		type = "Common",
		team = "Both",
		price = 300,
		rarity = "Common",
		effect = {
			duration = 5,
			radius = 10,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
	{
		id = "RandomTeleport",
		name = "随机传送器",
		description = "传送到随机安全点",
		type = "Common",
		team = "Both",
		price = 600,
		rarity = "Rare",
		effect = {
			teleportToSafeZone = true,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	{
		id = "ShieldPotion",
		name = "护盾药水",
		description = "减伤30%持续10秒",
		type = "Common",
		team = "Both",
		price = 400,
		rarity = "Uncommon",
		effect = {
			damageReduction = 0.3,
			duration = 10,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
	{
		id = "DoubleExpCard",
		name = "双倍经验卡",
		description = "本局经验x2",
		type = "Common",
		team = "Both",
		price = 500,
		rarity = "Uncommon",
		effect = {
			expMultiplier = 2,
			lastFullGame = true,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	
	-- ============ 找寻者专属道具 ============
	{
		id = "HighEnergyDetector",
		name = "高能探测仪",
		description = "显示15米内伪装物",
		type = "Seeker",
		team = "Seeker",
		price = 400,
		rarity = "Uncommon",
		effect = {
			detectRange = 15,
			duration = 3,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
	{
		id = "TrackingGrenade",
		name = "追踪手雷",
		description = "标记命中目标5秒",
		type = "Seeker",
		team = "Seeker",
		price = 350,
		rarity = "Common",
		effect = {
			markDuration = 5,
			explosionRadius = 5,
		},
		icon = "rbxassetid://0",
		maxStack = 3,
	},
	{
		id = "SonicPulse",
		name = "声波脉冲",
		description = "20米范围显形3秒",
		type = "Seeker",
		team = "Seeker",
		price = 0, -- 地图掉落
		rarity = "MapDrop",
		effect = {
			revealRange = 20,
			duration = 3,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	{
		id = "PowerBullet",
		name = "强化子弹",
		description = "伤害+50%持续30秒",
		type = "Seeker",
		team = "Seeker",
		price = 450,
		rarity = "Uncommon",
		effect = {
			damageBonus = 0.5,
			duration = 30,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	{
		id = "TeamBoost",
		name = "团队加速",
		description = "全体找寻者速度+20%",
		type = "Seeker",
		team = "Seeker",
		price = 800,
		rarity = "Rare",
		effect = {
			teamSpeedBonus = 0.2,
			duration = 15,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	
	-- ============ 躲藏者专属道具 ============
	{
		id = "Decoy",
		name = "木偶替身",
		description = "放置吸引火力的假身",
		type = "Hider",
		team = "Hider",
		price = 300,
		rarity = "Common",
		effect = {
			decoyHealth = 50,
			duration = 30,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
	{
		id = "FireworkDistraction",
		name = "烟花干扰器",
		description = "制造音效+闪光",
		type = "Hider",
		team = "Hider",
		price = 250,
		rarity = "Common",
		effect = {
			flashDuration = 2,
			soundRadius = 30,
		},
		icon = "rbxassetid://0",
		maxStack = 3,
	},
	{
		id = "TempRevive",
		name = "临时复活币",
		description = "原地复活(限非最后)",
		type = "Hider",
		team = "Hider",
		price = 800,
		rarity = "Rare",
		effect = {
			reviveOnSpot = true,
			notLastPlayer = true,
		},
		icon = "rbxassetid://0",
		maxStack = 1,
	},
	{
		id = "InvisCloak",
		name = "隐形斗篷",
		description = "隐身3秒",
		type = "Hider",
		team = "Hider",
		price = 500,
		rarity = "Uncommon",
		effect = {
			invisDuration = 3,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
	{
		id = "TransformRefresh",
		name = "变形刷新",
		description = "立即刷新变形CD",
		type = "Hider",
		team = "Hider",
		price = 350,
		rarity = "Uncommon",
		effect = {
			resetTransformCooldown = true,
		},
		icon = "rbxassetid://0",
		maxStack = 2,
	},
}

return Items